# これは、MusicBotの構成ファイルです。 ボットをセットアップするには、このファイルを編集する必要があります。
# メモ帳を使用してこのファイルを編集しないでください。
# 形式が損なわれるため、サクラエディタまたはVisual Studio Codeなどのコードエディターを使用してください。

# IDを取得するには、開発者モードを有効にします（オプション->設定->外観）
# Discordで、取得したい人/チャンネルを右クリックします
# チャンネル、[IDのコピー]をクリックします。 「listids」コマンドを使用することもできます。
# (http://i.imgur.com/GhKpBMQ.gif)


; さまざまなIDを取得する方法:
; http://i.imgur.com/GhKpBMQ.gif
; 開発者モード（オプション、設定、外観）を有効にし、IDが必要なオブジェクトを右クリックして、[IDのコピー]をクリックします。
; これは基本的に、IDが必要なすべてのもの（チャネルとユーザー）で機能します。 ロールについては、ロールのメンションを右クリックする必要があります。


[Credentials]
# これはDiscordボットアカウントトークンです。
# ここでボットのトークンを見つけます： https://discordapp.com/developers/applications/me/
# リダイレクトURIまたはボックスにチェックマークを付けずに、新しいアプリケーションを作成します。
# 次に、アプリケーションページで[ボットユーザーの作成]をクリックし、ここにトークンをコピーします。
Token = bot_token

# ボットは、SpotifyリンクとURIをYouTubeビデオに変換し、
# それらを再生します。 この機能を有効にするには、これら2つのオプションに有効な値を入力してください
# 詳細は、次の指示に従ってください。 https://just-some-bots.github.io/MusicBot/using/spotify/
Spotify_ClientID =
Spotify_ClientSecret =

# Yt-dlp OAuth2 プラグインで使用される YouTube API クライアント ID を設定します。
# 組み込みの認証情報が機能していない場合を除き、オプションです。
YtdlpOAuth2ClientID =

# Yt-dlp OAuth2 プラグインで使用される YouTube API クライアント シークレット キーを設定します。
# YtdlpOAuth2ClientID が設定されていない場合はオプションです。
YtdlpOAuth2ClientSecret =


[Permissions]
# このオプションは、どのユーザーがボットの完全な許可と制御を持っているかを決定します。
# 所有者は1人しか設定できませんが、permissions.iniを使用して他のユーザーに
# 他のコマンドへのアクセスを許可できます。
# このオプションを「auto」に設定すると、ボットの所有者がボットアプリケーションを作成した人に設定されます。 。
# これは通常、あなたが望むものです。
# それ以外の場合は、別のユーザーのIDに変更します
OwnerID = auto

# このオプションは、開発者専用コマンドにアクセスできるユーザーを決定します。
# 開発者専用コマンドは非常に危険であり、誤って使用するとボットが破損する可能性があるため、
# Pythonコードに精通していない限り、
# このオプションを無視することを強くお勧めします。
DevIDs =

# このオプションは、ボットが他のボットに応答するかどうかを決定します
# ボット ID をスペースで区切ってここに入力します
# ここに入力した ID には、ボットが応答します。
BotExceptionIDs =

[Chat]
# Discordチャットのコマンドの前に使用する必要があるプレフィックスを決定します。
# たとえば、これを*に設定すると、playコマンドは* playを使用してトリガーされます。
CommandPrefix = !

# ボットが特定のテキスト チャネルのみをリッスンするように制限します。
#これを使用するには、ボットにリッスンさせたいテキスト チャネルの ID をスペースで区切って追加します。
BindToChannels =

# BindToChannelsの動作を変更します。 通常、BindToChannelsにないチャネルに送信されたメッセージは無視されます。
# このオプションを使用すると、バインドされたチャネルを持たないサーバーでも、
# 他のサーバーでMusic Botの任意のチャネルでコマンドを使用できるように定義されたサーバーを使用できます。
# バインドされたチャネルがないときにyesに設定しても何も起こりません。
AllowUnboundServers = no

# ボットが起動時にサーバーに自動的に参加できるようにします。 これを使用するには、
# ボットが起動時に参加する音声チャネルのIDをスペースで区切って追加します。 各サーバーは1つのチャネルを持つことができます。
# このオプションとAutoSummonが有効になっている場合、このオプションが優先されます。
AutojoinChannels =

# ギルドに送信する代わりに、メッセージを再生するためのダイレクトメッセージを送信します。
# 再生中のメディアを追加したユーザーに送信されます。 現在、自動エントリのメッセージの再生は影響を受けず、
# NowPlayingChannelsの設定に従います。 ボットはダイレクトメッセージを削除しません。
DMNowPlaying = no

# 自動プレイリストを介して、ボットによって自動的に追加されたエントリのメッセージの再生を無効にします。
DisableNowPlayingAutomatic = no

# DMNowPlayingおよびDisableNowPlayingAutomaticの影響を受けないメッセージを再生するために、
# ボットが現在再生中のメッセージを出力するチャネルを決定します。 これがサーバーに指定されていない場合、
# 手動で追加されたエントリの再生メッセージは、ユーザーがコマンドを使用してそのエントリを追加するのと同じチャネルで送信され、
# 自動で追加されたエントリの再生メッセージは同じチャネルに送信されます 可能であれば、
# これがサーバーに指定されていない場合、最後に再生メッセージが送信されました。
# サーバーに複数のチャネルを指定すると、ボットはリストから1つのチャネルのみを選択してメッセージを送信します。
NowPlayingChannels =

# ボットは、以前に送信したメッセージをデフォルトで削除（または編集）しようとします。
# ボットがそれらを削除したくない場合（再生されたもののログを保持するため）、このオプションをオフにします。
DeleteNowPlaying = yes

[MusicBot]
# ボットのボリューム、0.01〜1.0。
DefaultVolume = 0.25

# MusicBot が再生するすべての曲にデフォルトで使用される再生速度。
# 0.5 から 100.0 までの値にする必要があります。
# デフォルトは 1.0 で、通常の再生速度です。
DefaultSpeed = 1.0

# 曲を正常にスキップするためにスキップに投票した人数。
# どちらか低い値が使用されます。比率は、チャンネル内の未承認の非所有者ユーザーの割合を示します。
SkipsRequired = 4
SkipRatio = 0.5

# ダウンロードしたビデオをaudio_cacheフォルダーに永続的に保存するかどうかを決定します。
# これが「はい」の場合、フォルダー内で検出されて再びキューに入れられた場合、それらは再ダウンロードされません。
# それ以外の場合、ビデオは一時的にフォルダにダウンロードされて再生され、スペースを埋めないように削除されます。
SaveVideos = yes

# 自動プレイリスト ファイルにリストされているビデオはキャッシュから削除されません。
# SaveVideos オプションが有効になっている場合にのみ適用されます。
StorageRetainAutoPlay = yes

# 保存されたファイルの時間制限を設定します。無効にするには 0 に設定します。
# この期間使用されていないファイルは削除されます。
# Linux/Mac では、最終アクセス時間が使用されます。Windows では、ファイル作成時間が使用されます。
# SaveVideos オプションが有効になっている場合にのみ適用されます。
StorageLimitDays = 0

# キャッシュ全体のサイズ制限を設定します。無効にするには 0 に設定します。
# 正確なバイト数または 20 MB などの省略表記を受け入れます
# ストレージがこのサイズを超えると、アクセス/作成時刻が古いファイルが最初に削除されます。
# SaveVideos オプションが有効になっている場合にのみ適用されます。
StorageLimitBytes = 0

# 曲の再生開始時にキューに入れたユーザーに言及します。
NowPlayingMentions = no

# 可能な場合、起動時に所有者の音声チャネルに自動的に参加します。
# ボットは同じサーバー上にあり、チャネルに参加する権限を持っている必要があります。
AutoSummon = yes

# チャンネルに参加した後、autoplaylist.txtファイルから曲の再生を開始します。
# これは、ユーザーが曲をキューイングするのを止めるものではありません。
# permissions.iniでコマンドアクセスを制限することで、それを行うことができます。
UseAutoPlaylist = yes

# 自動再生リストが有効なときに曲をランダムな順序で再生するかどうかを設定します。
# いいえの場合、曲は代わりに順番に再生されます。
AutoPlaylistRandom = yes

# ユーザーが新しい曲を再生したときに、自動再生リストの曲を自動的にスキップできるようにします。
# これは、自動再生リストによって追加された場合にのみ、現在再生中の曲に適用されます。
AutoPlaylistAutoSkip = yes

# 曲のブロックリストに曲が見つかった場合は、自動再生リストから曲を削除します。
AutoPlaylistRemoveBlocked = yes

# 誰かが再び参加するまで、音声チャンネルに誰もいないときに音楽を一時停止します。
AutoPause = yes

# しばらくしてからボットのメッセージを自動的にクリーンアップします。
DeleteMessages = yes

# これとDeleteMessagesが有効な場合、ボットはコマンドを呼び出した他のユーザーからのメッセージも削除しようとします。
# ボットには、このための「メッセージの管理」権限が必要です。
DeleteInvoking = no

# 定期的にキューをディスクに保存します。 その後、ボットがシャットダウンされると、
# キューは中断したところから再開します。
PersistentQueue = yes

# 曲の再生中に MusicBot がキュー内の次の曲をダウンロードできるようにします。
# 現在、このオプションは自動プレイリストや空のキューに追加された曲には適用されません。
PreDownloadNextSong = yes

# コンソールに記録するメッセージを決定します。
# デフォルトのレベルはINFOです。これは、平均的なユーザーが必要とするすべてのものです。
# 他のレベルには、CRITICAL, ERROR, WARNING, DEBUG, VOICEDEBUG, FFMPEG, NOISY,およびEVERYTHINGが含まれます。
# デバッグしている場合、またはボットのコンソール出力をより静かにする場合にのみ、これを変更する必要があります。
DebugLevel = INFO

# ボットのステータスとして使用するカスタムメッセージを指定します。
# 空のままにすると、ボットは現在再生中の音楽に関する動的な情報を代わりに表示します。
# Status messages may also use the following variables in custom status messages:
#  {n_playing}   = Number of currently Playing music players.
#  {n_paused}    = Number of currently Paused music players.
#  {n_connected} = Number of connected music players, in any player state.
#
# The following variables give access to information about the player and track.
# These variables may not be accurate in multi-guild bots:
#  {p0_length}   = The total duration of the track, if available. Ex: [2:34]
#  {p0_title}    = The track title for the currently playing track.
#  {p0_url}      = The track url for the currently playing track.
StatusMessage = 

# 有効にすると、ステータス メッセージの更新によって一時停止中のプレイヤーがカウントされ、報告されます。
StatusIncludePaused = no

# ボットが現在再生しているものをdata/<server id>/current.txtファイルに書き込みます。
# これは、OBSおよび動的入力を受け取る他のすべてで使用できます。
WriteCurrentSong = no

# 所有者がすべての曲を即座にスキップできる機能と同様に、曲をキューに入れた人が自分の曲を即座にスキップできるようにします。
AllowAuthorSkip = yes

# 実験的なイコライゼーションコードを有効にします。
# これにより、最初に曲を再生しているときに、処理の消費が大きくなりますが、すべての曲の音量が同じように聞こえます。
UseExperimentalEqualization = no

# ボット全体で埋め込みを使用できるようにします。
# これらはきれいに見えるようにフォーマットされたメッセージですが、
# Discord設定でリンクプレビューが無効になっているユーザーには表示されません。
UseEmbeds = yes

# queueコマンドの使用時に表示するアイテムの量。
QueueLength = 10

# 曲の再生中にエラーが発生した場合、オートプレイリストから曲を削除します。
# 有効にすると、再生できない曲は別のファイルに移動され、自動再生リストから削除されます。
# インターネットの問題または曲の再生で頻繁に問題が発生する場合は、これを無効にすることができます。
RemoveFromAPOnError = yes

# 起動時にボットの構成をコンソールに表示するかどうか。
ShowConfigOnLaunch = no

# レガシースキップ動作を使用するかどうか。 これにより、権限のある人が「skip f」を使用して曲を強制スキップする必要がなくなり、
# 代わりにデフォルトで強制スキップされます。
LegacySkip = no

# オーナーが見つからない場合はサーバーを離れます。
LeaveServersWithoutOwner = no

# aliases.jsonで定義されているコマンドエイリアスを使用します。
UseAlias = yes

# 検索コマンドの結果を表示するには別の方法を使用します。
SearchList = no

# デフォルトで返される検索結果の量を設定します。
DefaultSearchResults = 3

# 'setprefix' コマンドを使用して、ギルドごとのコマンドプレフィックスのオーバーライドを許可します。
EnablePrefixPerGuild = no

# 文字列を",'等で囲まないでください。不要です。 CustomEmbedFooterURLではエラーとなります。
# Botの埋め込みフッターに使用するカスタムメッセージ
CustomEmbedFooter = 
# Botの埋め込みフッターに使用するカスタムURL
CustomEmbedFooterURL = https://github.com/Just-Some-Bots/MusicBot

# ボイスチャンネルに参加するときにボットの音声を消すかどうかを設定します。
SelfDeafen = yes

# ボイスチャンネルが空になったときにボットがボイスチャンネルを離れるかどうかを設定します。
LeaveInactiveVC = no

# ボットが非アクティブな音声チャンネルを離れるまでの待機時間を設定します。
# LeaveInactiveVC が有効な場合にのみ適用されます。
# 時間は秒単位で設定するか、日、時間、分、秒のいずれかを含む期間フレーズとして設定できます。
# 例:
# .5 時間、1 日、77 分
# デフォルト値は 300 秒です。
LeaveInactiveVCTimeOut = 300

# すべての曲の再生が終了したらボットがすぐ終了するかどうかを設定します。
LeaveAfterQueueEmpty = no

# プレーヤーが一時停止またはプレイを停止できる秒数を設定します。この時間が経過するとプレーヤーは切断されます。
# この設定は LeaveAfterQueueEmpty とは無関係です。
# 時間は秒数で設定することも、LeaveInactiveVCTimeOut で説明されている期間を使用して設定することもできます。
# 無効にするには 0 に設定します。デフォルト値は 0 です。
LeavePlayerInactiveFor = 0

# ラウンドロビンキュー
# 有効にすると、ボットはユーザーがリクエストした曲を自動的に切り替えます。
RoundRobinQueue = no

# この設定により、ユーザーブロックリストの使用をすばやく有効または無効にすることができます。
EnableUserBlocklist = yes

# この設定により、Song Blocklist の使用をすばやく有効または無効にすることができます。
EnableSongBlocklist = no

# MusicBot がシステム ping コマンドを使用してネットワークの停止と可用性を検出できるようにします。
# これは、ボットをチャネルに接続したままにしたり、24 時間 365 日音楽を再生したりする場合に役立ちます。
# ネットワーク テストを有効にするには、MusicBot を再起動する必要があります。
# デフォルトでは無効になっています。
EnableNetworkChecker = no

# MusicBot によって再生されたすべての曲をグローバル プレイリスト history.txt に保存できるようにします
SavePlayedHistoryGlobal = no

# MusicBot が再生した曲をギルドごとのプレイリスト history-{Guild_ID}.txt に保存できるようにします
SavePlayedHistoryGuilds = no

# 再生コマンドを使用して、ローカル メディア ファイルの再生を有効にします。
# 有効にすると、ユーザーは `play file://path/to/file.ext`
# を使用して、ローカル MediaFileDirectory パスからファイルを再生できます。
EnableLocalMedia = no

# 再生コマンドが使用されたときに MusicBot が自動的に一時停止を解除できるようにします。
UnpausePlayerOnPlay = no

# ytdlp メディア ダウンローダーで使用する実験的な HTTP/HTTPS プロキシ設定。
# ここで設定された値は、`ytdlp --proxy` および aiohttp ヘッダー チェックに渡されます。
# 無効にするには空白のままにします。
YtdlpProxy = 

#yt-dlp で静的な User-Agent ヘッダーを設定するための実験的なオプションです。
# yt-dlp では通常、UA 文字列を変更することは推奨されません。
# ここに入力する内容の例については、次の 2 つのリンクを確認してください:
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
# https://www.useragents.me/
# 空白のままにすると、デフォルトの動的に生成された UA 文字列が使用されます。
YtdlpUserAgent = 

# yt-dlp が OAuth2 経由で YouTube アカウントを使用できるようにする試験的なオプション。
# 有効にすると、生成された URL とコードを使用してアカウントを認証する必要があります。
# 認証トークンは `data/auth.token` ファイルに保存されます。
# Cookie が有効になっている場合はこのオプションを使用しないでください。
# 個人アカウントの使用は推奨されない場合があります。
YtdlpUseOAuth2 = no

# 起動時に OAuth2 認証をトリガーするために使用されるオプションの YouTube URL。
# これにより、曲のリクエストを待つのではなく、OAuth2 プロンプトが早期に開始されます。
# これが設定されている場合は、起動を続行する前に認証を完了する必要があります。
YtdlpOAuth2URL = 


#独自BGM枠用指定時間カットモード
BgmWakuMode = no
#BGM枠再生時間(秒|s)
BgmLength = 120


[Files]
# 再起動時に自動ログ ファイルのローテーションを設定し、保持するファイルの数を制限します。
# 無効にすると、1 つのログのみが保持され、その内容は実行ごとに置き換えられます。
# デフォルトは 0、つまり無効です。最大許容数は 100 です。"
LogsMaxKept = 0

# LogsMaxKept が有効な場合に使用されるログ ファイルの日付形式を設定します。
# 空白のままにすると、警告がログに記録され、代わりにデフォルトが使用されます。
# テーブルとデータの時間形式コードの詳細については、次のリンクを参照してください:
# https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior
# デフォルト値は ".ended-%Y-%j-%H%m%S" です
LogsDateFormat = .ended-%Y-%j-%H%m%S

# i18nファイルへのパス。 何をするのかわからない場合は、これを設定しないでください。
i18nFile = 

# ダウンロードしたメディア ファイルを保存するフォルダー パス。空のままにしておくこともできます。
# このディレクトリが存在しない場合は作成されます。
# デフォルトのフォルダーは、現在の作業ディレクトリの「audio_cache」という名前です。
# このディレクトリは、SaveVideos が無効になっている場合でも一時的な保存に使用されます。
AudioCachePath = 

# Discord ユーザー ID 番号を追加して、それらのユーザーがボット コマンドを使用できないようにするファイル パス。
# デフォルトのファイルの場所を使用するには、このパスを空白のままにします。
# 存在しない場合は、MusicBot によって作成されます。
# デフォルト ファイル: config/blocklist_users.txt
UserBlocklistFile = 

# URL、動画 ID、その他の単語やフレーズを追加できるファイル パス
# URL または曲のタイトルにこのブロック リスト ファイルと一致する行が含まれている場合にユーザーがトラックを再生できないようにします。
# デフォルトのファイルの場所を使用するには、このフィールドを空白のままにします。
# 存在しない場合は MusicBot によって作成されます。
# デフォルト ファイル: config/blocklist_songs.txt
SongBlocklistFile = 

# プレイリストと関連ファイルを保存できるディレクトリ パス。
# デフォルトのパスは config/playlists/ です。
AutoPlaylistDirectory =

# 再生可能なメディア ファイルを保存できるオプションのディレクトリ パス。
# すべてのファイルとサブディレクトリには、プロトコルとして 'file://' を使用してアクセスできます。
# 例: file://some/folder/name/file.ext
# マッピング先: ./media/some/folder/name/file.ext
MediaFileDirectory =
